---
- name: Render Jinja Template
  hosts: localhost
  vars:
    color: blue
    car: mustang
    switches: [sw1,sw2,sw3]
  vars_files:
    - variables.yml

  tasks:

  - name: Template a file
    ansible.builtin.template:
      src: render.j2
      dest: outputfile.txt